server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: meizhu
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true

mybatis-plus:
# XML 文件位置
  mapper-locations: classpath*:mapper/*/*.xml
# MyBaits 别名包扫描路径
  type-aliases-package: com.hyl.mybatisplus.entity
  global-config:
    # 修改xml文件自动刷新
    refresh: true
    # 表名、是否使用下划线命名
    table-underline: true
  # sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置文件
logging:
  config: classpath:log4j/log4j2.xml